### ISSUE TITLE
SqlClient: Support SqlAuthenticationProvider and authentication connection string keyword for AAD auth

### ISSUE THREAD

**Issue by gabarach** [dotnet/SqlClient#10]
AAD authentication, including MFA, is already supported on SqlClient for .NET Core from version 2.2, by first obtaining the AccessToken using the [ADAL library](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet) or some other method against Azure AD, and then setting it on the AccessToken property of the SqlConnection. 

This issue is about enabling a different pattern for AAD authentication that is supported in .NET Framework, in which SqlClient takes care of obtaining the AccesToken automatically based on an authentication keyword in the connection string and SqlAuthenticationProvider implemetnations. 

### Original issue text
Please add AAD auth support for Azure SQL Database the way how that' s supported in .NET framework 4.6. We should be able to use Authentication modes like "Active Directory Integrated" and "Active Directory Password" in the connecting string.
Currently, including aforementioned authentication modes result into following error:
“Keyword not supported: ‘authentication’.

**Comment by nimitad** [comment]
> Yeah, I got it working too some while ago.
> 
> ```cs
>  services.AddScoped<DbContext>(p =>
>                     {
>                         var ctx = new AuthenticationContext("https://login.microsoftonline.com/xxx");
> 
>                         var result = ctx.AcquireTokenAsync("https://database.windows.net/", new ClientCredential("xxx", "xxx"))
>                             .ConfigureAwait(false)
>                             .GetAwaiter()
>                             .GetResult();
> 
>                         var db = p.GetService<MyDbContext>();
> 
>                         ((SqlConnection)db.Database.GetDbConnection()).AccessToken = result.AccessToken;
> 
>                         return db;
> 
>                     });
> ```

Hi - What is "xxx" supposed to be in "var ctx = new AuthenticationContext("https://login.microsoftonline.com/xxx");"

**Comment by David-Engel** [comment]
@nimitad It's the authority you are authenticating against:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AuthenticationContext-the-connection-to-Azure-AD#authority-validation

**Comment by srinuece60** [comment]
Is .net core 2.2 web api can work for SQL with Azure AD Password Authentication.
I am facing the error "Exception: Keyword not supported: 'authentication'"

**Comment by cheenamalhotra** [comment]
@srinuece60 

Have you tested with latest preview version of [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) ?

**Comment by divega** [comment]
@cheenamalhotra FWIW, I just tested this with https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.0.19189.1-Preview and I still see the exception when targeting .NET Core:

> System.ArgumentException: Keyword not supported: 'authentication'. 

Is this supposed to be addressed?

**Comment by srinuece60** [comment]
> @srinuece60
> 
> Have you tested with latest preview version of [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) ?

Yes. I tested with that, still same issue

**Comment by cheenamalhotra** [comment]
@divega 

I get it now. The work is in progress for .NET Core support, we only have it working for applications targeting .NET Framework as of now. Likewise the issue is addressed in our backlog and planned for GA. I will mark it accordingly in Kanban board to avoid any confusions.

**Comment by crgarcia12** [comment]
It worked for me doing this from an Azure App Service using MSI.

            string token = (new Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider()).GetAccessTokenAsync("https://database.windows.net/").Result;           

            using (SqlConnection con = new SqlConnection("Server=tcp:<servername>.database.windows.net,1433;Database=<dbname>;"))
            {
                con.AccessToken = token;
                con.Open();



I got these packages added to my project:
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview7.19362.9" />

**Comment by adria3a3** [comment]
Is there an ETA for this issue?

**Comment by srinuece60** [comment]
> @srinuece60
> 
> Have you tested with latest preview version of [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) ?

I taken the latest version of SQlclient. but my issue is not solved. 
Again I tried with the below way now It's working for me.

I created one Azure App with the name of 'CoreApp'. then I added user with the same name of Azure App name 'CoreApp' in Azure SQL Server and granted the permissions for that user by using the below commands.

![image](https://user-images.githubusercontent.com/5112055/62609367-425c9800-b91f-11e9-85de-4d722f58e4af.png)


Then I used the below code in Web API under Startup.CS file with in the method of 'services.AddDbContext<DBContext>'

![image](https://user-images.githubusercontent.com/5112055/62609197-f3aefe00-b91e-11e9-95eb-2b6b7598f925.png)

Now I am able to access the Azure SQL with AD passwords authentication with in .net core 2.0

**Comment by cheenamalhotra** [comment]
@adria3a3 @divega @gabarach 

Active Directory Password Authentication support has been added to Microsoft.Data.SqlClient (NetCore) in the latest preview version [1.0.19221.1-Preview](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.0.19221.1-Preview) | [Release Notes](https://github.com/dotnet/SqlClient/blob/master/release-notes/1.0/1.0.19221.1-Preview.md).

Closing the issue.

**Comment by abjoseph** [comment]
> @adria3a3 @divega @gabarach
> 
> Active Directory Password Authentication support has been added to Microsoft.Data.SqlClient (NetCore) in the latest preview version [1.0.19221.1-Preview](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.0.19221.1-Preview) | [Release Notes](https://github.com/dotnet/SqlClient/blob/master/release-notes/1.0/1.0.19221.1-Preview.md).
> 
> Closing the issue.

@cheenamalhotra, could you point a fellow developer to either the source code/merge request that implemented the change to support the Active Directory Password Authentication method. 

I've made sure to read through this entire thread and there were no examples **specifically** geared to this approach using .NET Core, specifically I referring to configuring the SqlConnection in .NET Core to use (what I assume ) the implemented provider for Active Directory Password Authentication.

Please correct me if i'm wrong and provide guidance otherwise.

**Comment by cheenamalhotra** [comment]
Hi @abjoseph 

Usage in NetCore for _AAD Password Authentication_ is identical to .Net Framework, and same connection string works for both targets. Existing Documentation: [Using an Azure AD identity to connect from a client application](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication-configure#using-an-azure-ad-identity-to-connect-from-a-client-application)

We are currently working on gathering documents for all existing and new features for M.D.SqlClient which will provide more clarity. We'll also add more details for _Interactive_ Authentication (which is currently supported in .Net Framework), but for now you can use the same connection string as Integrated Authentication connection string with `Active Directory Interactive` as value for `Authentication` connection property, without the need to provide accessToken or credentials.

For .NET Core to support _Interactive_ authentication, it is in our backlog and shall be picked up in future iterations, we were hitting some roadblocks from MSAL.NET hence its disabled for now. Whenever we touchbase again, _Integrated_ and _Interactive_ modes need to be re-investigated and hopefully will be supported for .NET Core in future driver versions.

Thanks for checking in!

**Comment by jeevanbalanmanoj** [comment]
@cheenamalhotra I believe putting the username and password in connection string won't work in .netcore. I get the following error 
 System.ArgumentException: 'Keyword not supported: 'authentication' 

Here is a summary of the issue that I'm facing. Any leads will be great. 


 We are trying to use .netcore sqlclient to connect to an Azure SQL server instance. We don’t have any control over the SQL server instance and hence can only do Active directory Password based authentication. Everything works perfectly in  .net framework with the following code.

SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();
builder.Authentication = SqlAuthenticationMethod.ActiveDirectoryPassword;

However, we aren’t able to do the same in .netcore as Authentication is not a valid property in the builder class.

Is there any way we can manually perform the token exchange in .net core? I’m using .netcore 2.2.401

**Comment by multco-malan** [comment]
I too would like this in .net core 2.2,
And would expect it to be available in .net core 3.x right out of the box,
Else i'm scrapping any applications using .net core and reverting back to full framework.

And no, I don't want to supply pwds either.

**_Would you have a link to the work task on getting "Authentication=Active Directory Integrated" working in .net core?_**
