### ISSUE TITLE
Error code 139 when attempting Microsoft.Data.SqlClient connection on Linux with net6.0

### ISSUE THREAD

**Issue by rytido** [dotnet/SqlClient#1390]
I get error code 139 when attempting Microsoft.Data.SqlClient connection on Linux with net6.0 (6.0.100). I see the error when using `dotnet watch run`, otherwise it exits silently. The same code works on net5.0.

```
watch : Exited with error code 139
```
### To reproduce

app.fsproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="3.0.1" />
  </ItemGroup>

</Project>
```

Program.fs
```
open System
open Microsoft.Data.SqlClient

let server = Environment.GetEnvironmentVariable("SERVER")
let connectionString = $"Server={server};Trusted_Connection=True;"

let cnxn = new SqlConnection(connectionString)

cnxn.Open() // program silently exits here (or with code 139 if using watch)
printf "connection is open"
cnxn.Close()
```

**Comment by JRahnama** [comment]
@rytido thanks for bringing this up. Using UID and PWD will solve the issue.

```C#
open System
open Microsoft.Data.SqlClient

let connectionString = "Data Source=127.0.0.1;UID=<user name>;PWD=<password>;"
let cnxn = new SqlConnection(connectionString)
exception Error1 of string
try
cnxn.Open()
Console.WriteLine(cnxn.State)
cnxn.Close()
Console.WriteLine(cnxn.State)
with
| Error1(str) -> printfn "Error1 %s" str

```

**Comment by rytido** [comment]
Did Kerberos auth support get dropped? I cannot necessarily use sql server auth. This worked in net5.0.

**Comment by JRahnama** [comment]
@rytido I will test with Kerberos and will update you soon.

**Comment by JRahnama** [comment]
something to mention here about a [breaking change on net 6 and kerberos](https://docs.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/httpclient-port-lookup) . Port  has been removed from SPN for Kerberos and Negotiate. I made a C# application with net 6 and kerberos and got the same results as yours. F# acted the same. When I used user name and password everything worked fine.

**Comment by rytido** [comment]
That's not the issue for two reasons: 
1. If I revert to `netcoreapp3.1` my app works, and that doc indicates 3.x behavior should be the same as 6. 
2. I set the env var `DOTNET_SYSTEM_NET_HTTP_USEPORTINSPN=1`, and just to be certain also set the context switch `AppContext.SetSwitch("System.Net.Http.UsePortInSpn", true)`. The net6 version of this still crashes.

**Comment by stcpottdav** [comment]
I am having the same issue.  After running a test, I used dmesg to show where the segmentation fault happened:
dotnet[659]: segfault at 0 ip 00007fdc7e8a63bc sp 00007ffe5b10db70 error 4 in libSystem.Net.Security.Native.so[7fdc7e8a6000+1000]

**Comment by JRahnama** [comment]
@roji have you seen similar issue with net 6 and Kerberos?  I have tested with `Microsoft.Data.SqlClient` and `System.Data.SqlClient` using Kerberos authentication. Tested with `C#` and `F#` no exception is thrown. It just does not work, no results come back and it gets terminated. The [documentation ](https://docs.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/httpclient-port-lookup) suggests adding a switch will fix the issue. I tested with the switch and environment variable, no luck so far. Just wanted to check with you.

Thank you.

**Comment by rytido** [comment]
May also be worth noting that in an AspNetCore app this doesn't just make a single request fail, it silently kills the whole service.

**Comment by wfurt** [comment]
I think this is dup of https://github.com/dotnet/runtime/issues/60906. The linked breaking change only impact HttpClient in cases it tries to generate SPN on it's own.

**Comment by wfurt** [comment]
BTW it may be best (fastest) to update SqlClient to react to https://github.com/dotnet/runtime/pull/55037.

**Comment by JRahnama** [comment]
thanks @wfurt. Although the issue seems external according to the [link you posted](https://github.com/dotnet/runtime/issues/60906). I'll do more debugging to see why no exception is thrown

**Comment by wfurt** [comment]
for runtime, we call `EnsureGssInitialized` via static constructor. That will load all the function pointers. AFAIK `SqlClient` does not do it so it would crash (dereferencing NULL in gssapi code) when trying to use the functions. If you call `NetSecurityNative_EnsureGssInitialized` once, the crash should go away. Let me know if that make sense @JRahnama.

**Comment by JRahnama** [comment]
@wfurt thanks for the update. I added the `EnsureGssInitialized`  to SqlClient and it worked for net 6 and failed for net 5. Just to confirm this is expected correct? I mean that part of the code is only for net 6 and after if I am not mistaken.

**Comment by wfurt** [comment]
yes, this was done late (unfortunately) in 6.0. So either wrap it In try/catch or even better 
```c#
if (Environment.Version.Major >= 6)
{
    EnsureGssInitialized();
}
```
Long run, I would like to add enough public surface so SqlClient (and others) do not need to depend on private functions.
We missed 6.0.1 maintenance and next one will be early next year. If you can do anything faster it would be great @JRahnama.
If there is new package available, please ping both threads so people can try it.

**Comment by JRahnama** [comment]
Unfortunately we are releasing GA version 4.0 today and most of the documents are prepared without this fix included, but we can arrange a hotfix release for near future. It needs our PM, @David-Engel , approval.

**Comment by wfurt** [comment]
ok. That would still probably be much faster than runtime. 
Adding @karelz and @danmoseley  for visibility.

**Comment by thestonehead** [comment]
If someone didn't think of this, I cloned the repo and added 
`       
        [DllImport(Interop.Libraries.NetSecurityNative, EntryPoint = "NetSecurityNative_EnsureGssInitialized")]
        internal static extern int EnsureGssInitialized();


        static NetSecurityNative()
        {
            EnsureGssInitialized();
        }
`
to _src/Microsoft.Data.SqlClient/netcore/src/Common/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.cs
_

and packaged homemade nuget and put it in our local repository to use until official fix is available.

**Comment by danmoseley** [comment]
As noted above, we just missed 6.0.1, and with the holiday period, 6.0.2 is not expected to ship until the 2nd week of Feb.

**Comment by JRahnama** [comment]
We are planning on a hotfix from our side sometime soon. Time will be announced soon.

**Comment by JRahnama** [comment]
@rytido, @thestonehead can you try with [this build](https://dev.azure.com/sqlclientdrivers-ci/_apis/resources/Containers/15158758/Nuget?itemPath=Nuget%2FMicrosoft.Data.SqlClient.4.0.0-pull-e05ce4a.21330.4.nupkg) and let me know if that works for you.

**Comment by aletsche** [comment]
We face the same issue when using the container image "ubi8/dotnet-60" from Red Hat and trying to connect to a MSSQL database using Kerberos with the code shown below. Using "ubi8/dotnet-50" everthing works as expected. 

```
sh-4.4$ cat Program.cs
using System;
using System.Data.SqlClient;
using System.Text;

namespace sqltest
{
    class Program
    {
        static void Main(string[] args)
        {
            try 
            {
                while (true) 
                {
                    String connectionString = Environment.GetEnvironmentVariable("DATABASE_URL");
                    String sql = Environment.GetEnvironmentVariable("DATABASE_QUERY");
                    
                    using (SqlConnection connection = new System.Data.SqlClient.SqlConnection(connectionString))
                    {
                        Console.WriteLine("\nQuery data example:");
                        Console.WriteLine("=========================================\n");

                        connection.Open();       

                        using (SqlCommand command = new SqlCommand(sql, connection))
                        {
                            using (SqlDataReader reader = command.ExecuteReader())
                            {
                                while (reader.Read())
                                {
                                    for (int i = 0; i < reader.FieldCount; i++)
                                    {
                                        if (i > 0) { Console.Write(", "); }
                                        Console.Write(reader.GetValue(i));
                                        
                                    }
                                    Console.WriteLine();
                                }
                            }
                        }                    

                        connection.Close();
                    }
                    System.Threading.Thread.Sleep(30000); 
                }
            }
            catch (SqlException e)
            {
                Console.WriteLine(e.ToString());
            }
        }
    }
}
sh-4.4$
````

**Comment by JRahnama** [comment]
@aletsche the issue exists on `Microsoft.Data.SqlClient` and `System.Data.SqlClient` when using net 6. The [proposed fixed](https://dev.azure.com/sqlclientdrivers-ci/_apis/resources/Containers/15158758/Nuget?itemPath=Nuget%2FMicrosoft.Data.SqlClient.4.0.0-pull-e05ce4a.21330.4.nupkg) is for `Microsoft.Data.SqlClient`. Is it possible for you to test with MDS and let us know if it works for you.

**Comment by aletsche** [comment]
@JRahnama unfortunately I don't have any possibility to test with MDS personally. Will ask a colleague tomorrow .. he might have the necessary environment to test

**Comment by stcpottdav** [comment]
I would test if I could but I get access denied when trying to access https://dev.azure.com/sqlclientdrivers-ci/_apis/resources/Containers/15158758/Nuget?itemPath=Nuget%2FMicrosoft.Data.SqlClient.4.0.0-pull-e05ce4a.21330.4.nupkg

**Comment by McMlok** [comment]
I have same issue and I would test too, but I don't have access to nuget mentioned above. Thank you.

**Comment by JRahnama** [comment]
[Microsoft.Data.SqlClient.4.0.0-pull-e05ce4a.21330.4.zip](https://github.com/dotnet/SqlClient/files/7644941/Microsoft.Data.SqlClient.4.0.0-pull-e05ce4a.21330.4.zip)
change from .zip to .nupkg

**Comment by stcpottdav** [comment]
My tests worked.  Will there be something official package on nuget.org with these changes?

**Comment by MrRickwi** [comment]
Hi, we are facing exact the same problem. Using the Microsoft.Data.SqlClient assembly mentioned above helped. Additionally, we had to set TrustServerCertificate=true on connection string to get the app ported from .NET 5 (working) to .NET 6 (initially not working, working with both fixes). Getting an official version as soon as possible is recommended.

**Comment by clbiggs** [comment]
We have been getting this issue as well. Couldn't use the assembly above since it's all done through EF in the application, but we did get a temporary work around until the an official update that can replace the downstream nuget package.

Adding the EnsureGssInitialized() method call in the program.cs stopped the error.

```
    public class Program
    {        
        [DllImport("System.Net.Security.Native", EntryPoint = "NetSecurityNative_EnsureGssInitialized")]
        internal static extern int EnsureGssInitialized();
        
        public static void Main(string[] args)
        {
            if(OperatingSystem.IsLinux()) 
                EnsureGssInitialized();
                
            CreateHostBuilder(args).Build().Run();
        }

    // builder code etc...

    }
```

**Comment by stcpottdav** [comment]
Will the official fix be released before May when support for .NET 5 ends?

**Comment by JRahnama** [comment]
@stcpottdav we are planning a hotfix release around January 15 of 2022. The release will include some other fixes as well.

**Comment by natilivni** [comment]
@DavoudEshtehari, any idea when this fix will be released?

**Comment by DavoudEshtehari** [comment]
[It's already scheduled for [Jan 14](https://github.com/dotnet/SqlClient/milestone/33).](https://github.com/dotnet/SqlClient/pull/1411#issuecomment-1009351682)

**Comment by sandi91** [comment]
Hey everyone. Issue is still occuring in .net 6.0.2. All the used nuget packages were also updated to 6.0.2 besides dotnet itself.

**Comment by wfurt** [comment]
The fix is not in .NET @sandi91 so the version does not matter. You need to make sure you have the updated Microsoft.Data.SqlClient.

**Comment by ajansveld** [comment]
Quoted from [Introducing the new Microsoft.Data.SqlClient](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/)

> It means the development focus has changed. We have no intention of dropping support for System.Data.SqlClient any time soon. It will remain as-is and we will fix important bugs and security issues as they arise. If you have a typical application that doesn’t use any of the newest SQL features, then you will still be well served by a stable and reliable System.Data.SqlClient for many years.

Since this issue now prevents people from upgrading from .NET 5 to .NET 6, I would argue this is an "important bug". 

Will this fix be implemented in System.Data.SqlClient and shipped with .NET 6?

**Comment by danmoseley** [comment]
@DavoudEshtehari / @JRahnama /@david-engel  did/would you consider for backport to .NET 6?

**Comment by David-Engel** [comment]
We should definitely backport this to S.D.S.

**Comment by danmoseley** [comment]
@David-Engel the process is the same as last time you did this, but LMK if you need anything, eg., happy to represent this in tactics if you do the template in the PR

**Comment by danmoseley** [comment]
BTW, this would be for 6.0.4 to release in April. Meantime perhaps someone would like to explicitly paste in the code necessary to workaround, that was mentioned above, for the ease of others.

**Comment by JRahnama** [comment]
@danmoseley we are working on a PR to back port the fix to SDS.

**Comment by JRahnama** [comment]
I am reopening this issue to keep a track on all other interconnected issues.

**Comment by ErikEJ** [comment]
@ladeak as an alternative you can use this package with MDS 4 

https://www.nuget.org/packages/ErikEJ.EntityFramework.SqlServer/

**Comment by cli00004** [comment]
Hi Just wondering if this issue is fixed? I'm still experiencing the same issue with latest Microsoft.Data.SqlClient 4.1.0

**Comment by duyn9uyen** [comment]
I've been struggling trying to upgrade our .NET 5 API to .NET 6 with for days! We host our API on a Linux containers in Kubernetes. The container kept crashing and I saw that it threw a `Segmentation fault (core dumped).` error. Explicitly referencing Microsoft.Data.SqlClient 4.1.0 worked for me!

**Comment by JRahnama** [comment]
@duyn9uyen the problem was addressed in v4.1.

**Comment by Palsternakka** [comment]
I'm having the same issue with a .NET Core app on Xubuntu - as soon as a connection is attempted the app throws a segmentation fault (connection string `Data Source=10.1.3.7;Initial Catalog=CreditsafeProcessing;Integrated Security=true`)

Project is using Microsoft.EntityFrameworkCore.SqlServer version 6.0.7, run using .NET Core version 6.0.302

I've run `kinit` successfully so based on all my reading it should work? Further details [here](https://github.com/microsoft/azuredatastudio/issues/20225)

**Comment by JRahnama** [comment]
@Palsternakka Microsoft.EntityFrameworkCore.SqlServe is using M.D.SqlClient v2.1.4. Can you overwrite the version in the csproj file by adding packageReference to version 4.1? The issue was addressed first in v4.0.1 and is not back ported to previous versions yet.
```C#
<ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
</ItemGroup>
```

**Comment by hameedshk** [comment]
After lot of debugging , below code fix works for me in .net 6.0 framework.

Environment - openshift red hat OS and slq server authentication in Kerberos mode 

**.csproj change** 
`
<PackageReference Include="System.Data.SqlClient" Version="4.8.2" />`

**Program.cs change**
```
public class Program
    {
         [DllImport("System.Net.Security.Native", EntryPoint = "NetSecurityNative_EnsureGssInitialized")]
        internal static extern int EnsureGssInitialized();
        /// <summary>
        /// Main method
        /// </summary>
        /// <param name="args"></param>
        public static void Main(string[] args)
        {
          if (OperatingSystem.IsLinux())
                {
                    System.Console.WriteLine("Ensuring Gss is Initialized ({ApplicationContext})...");
                    EnsureGssInitialized();
                }
            CreateHostBuilder(args).Build().Run();
        }

```
**Startup.cs change**
```
public void ConfigureServices(IServiceCollection services)
{
  services.AddDataProtection()
 .PersistKeysToFileSystem(new DirectoryInfo(@"/opt/app-root/.aspnet/DataProtection-Keys"));       
    
 ```

**Comment by Palsternakka** [comment]
> @Palsternakka Microsoft.EntityFrameworkCore.SqlServe is using M.D.SqlClient v2.1.4. Can you overwrite the version in the csproj file by adding packageReference to version 4.1? The issue was addressed first in v4.0.1 and is not back ported to previous versions yet.
> 
> ```cs
> <ItemGroup>
>       <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
> </ItemGroup>
> ```

This worked for me, thank you!

**Comment by hameedshk** [comment]
> > @Palsternakka Microsoft.EntityFrameworkCore.SqlServe is using M.D.SqlClient v2.1.4. Can you overwrite the version in the csproj file by adding packageReference to version 4.1? The issue was addressed first in v4.0.1 and is not back ported to previous versions yet.
> > ```cs
> > <ItemGroup>
> >       <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
> > </ItemGroup>
> > ```
> 
> This worked for me, thank you!

I did try this because as I see the somewhere in the thread this issue is reported , unfortunately this didn’t work for me , may be I missed something in between

**Comment by IOnlyFetchBranches** [comment]
Just wanna mention 


> > @Palsternakka Microsoft.EntityFrameworkCore.SqlServe is using M.D.SqlClient v2.1.4. Can you overwrite the version in the csproj file by adding packageReference to version 4.1? The issue was addressed first in v4.0.1 and is not back ported to previous versions yet.
> > ```cs
> > <ItemGroup>
> >       <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
> > </ItemGroup>
> > ```
> 
> This worked for me, thank you!

This worked for us, running the dotnet6.0 runtime RHEL images. It is unfortunate this is not fixed though, any word on this from the devs?

**Comment by JRahnama** [comment]
@IOnlyFetchBranches the fix has been back ported to 2.1 version. You can overwrite the version in the csproj to 2.1.5 and probably that will fix the problem for you. You can see the release notes [here.](https://github.com/dotnet/SqlClient/blob/2.1-servicing/release-notes/2.1/2.1.5.md)
For System.Data.SqlClient the fix has been ported and will be available on the next release.

**Comment by carlossanlop** [comment]
All - FYI the fix introduced by [this PR](https://github.com/dotnet/corefx/pull/43133) has been published to the System.Data.SqlClient package in nuget: https://www.nuget.org/packages/System.Data.SqlClient/4.8.4

**Comment by JRahnama** [comment]
Closing the issue as the fix has been ported to System.Data.SqlClient v4.8.4 latest release.
