### ISSUE TITLE
SNI.dll file locked when ASP.NET (Framework 4.8) App is running in IIS

### ISSUE THREAD

**Issue by jakenuts** [dotnet/SqlClient#354]
### Describe the bug
The SNI.dll file is loaded/locked by IIS when using a Microsft.Data.SqlClient connection in a ASP.NET 4.8 Framework website but is not unloaded when the app is shutdown. Subsequent attempts to build or deploy the site are blocked by the error _Unable to delete file "bin\x86\SNI.dll". Access to the path '...\bin\x86\SNI.dll' is denied_. Every other dll in the bin folder can be deleted even while the web app is still running save for this one.

### To reproduce

1.) Create an ASP.NET MVC website on the 4.8 Framework
2.) Add the Microsoft.Data.SqlClient package
3.) In the HomeController.Index method open a SqlConnection and execute an arbitrary command
```c#
using (var connection = new SqlConnection("<connection string here>"))
{
    connection.Open();
    new SqlCommand("SELECT 1", connection).ExecuteNonQuery();
}
```
4.) Cause the site to shutdown by modifying the web.config or stopping the debugger. 
5.) The SNI.dll file remains locked and cannot be replaced or modified without shutting down IIS or the application pool associated with the website

### Expected behavior
The SNI.dll should be unlocked (like the rest of the files in the bin folder) so that a site can be updated through deployment or build.  

### Further technical details
Microsoft.Data.SqlClient version: v1.1.0
.NET target: Framework 4.8
SQL Server version: SQL Azure
Operating system: Windows 10 Professional / Windows Server 2016 Datacenter (Azure VM)

**Comment by jakenuts** [comment]
The SNI.dll library appears to be loaded in the [SNINativeMethodWrapper](https://github.com/dotnet/SqlClient/blob/d6f2e29cda769e711988c64d3cb57eb5010a3e9c/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs) static initializer but the handle is not kept or freed anywhere else in the code. 

``` c#
 IntPtr pDll = LoadLibrary(localFolder + subfolder + SNI);
 if (pDll == IntPtr.Zero)
 {
    throw new System.ComponentModel.Win32Exception("Failed to load " + localFolder + subfolder + SNI, 
   new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error()));
}

```

**Comment by cheenamalhotra** [comment]
@jakenuts 

Could you also verify and confirm if same behaviour is observed with System.Data.SqlClient?

**Comment by jakenuts** [comment]
I tried removing the SqlClient packages, changing the using statement to using System.Data.SqlClient which creates a SqlConnection from the System.Data 4.0.0 framework assembly and no SNI.dll is copied to the bin folder so no issues there.

I tried installing the System.Data.SqlClient 4.8 package and it does not appear to rely on a SNI.dll for this 4.8 project and all the files in the bin folder can be deleted while the web app is running. 

I then replaced that package with Microsoft.Data.SqlClient but kept the using statement as "using System.Data.SqlClient". This copied the SNI.dll to the bin/x86 folder but it is not loaded or locked when executing the command. 

Changing the using statement to "using Microsoft.Data.SqlClient" and running the app caused the SNI.dll to be loaded and it is locked until I terminate the IIS process.

**Comment by jakenuts** [comment]
I tried some alternative setups where the data call DoData() was moved to a .NET Standard 2.0 library as that's the one my project uses. It demonstrated the "could not load file or assembly" error that shows up alot in Google searches, performed as expected when both project referenced System.Data.SqlClient 4.8, but moving to them both the Microsoft.Data.SqlClient replicates the file locking issue above.

[Setup 1]

ASP.NET NET 4.8 Project
- no data assemblies referenced

.NET Standard 2.0 Library
- System.Data.SqlClient 4.8 referenced
- Using System.Data.SqlClient


> No SNI dll in bin 
> Calling DoData() from the webapp into the library generates

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Data.SqlClient, Version=4.6.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

[Setup 2]

ASP.NET NET 4.8 Project
- System.Data.SqlClient 4.8 referenced

.NET Standard 2.0 Library
- System.Data.SqlClient 4.8 referenced

> No SNI dll in bin 
> Calling DoData() from the webapp into the library succeeds, all files can be deleted


[Setup 3]

ASP.NET NET 4.8 Project
- no data assemblies referenced

.NET Standard 2.0 Library
- Microsoft.Data.SqlClient 1.1.0 referenced
- using Microsoft.Data.SqlClient;

> No SNI dll in bin 
> Calling DoData() from the webapp fails with the 'could not load' exception


[Alternate Setup 4]

ASP.NET NET 4.8 Project
- System.Data.SqlClient 4.8 referenced

.NET Standard 2.0 Library
- Microsoft.Data.SqlClient 1.1.0 referenced
- using Microsoft.Data.SqlClient;

> No SNI dll in bin 
> Calling DoData() from the webapp fails with the 'could not load' exception


[Alternate Setup 4]

ASP.NET NET 4.8 Project
- Microsoft.Data.SqlClient 1.1.0 referenced

.NET Standard 2.0 Library
- Microsoft.Data.SqlClient 1.1.0 referenced
- using Microsoft.Data.SqlClient;

> SNI dll copied to bin
> Calling DoData() succeeds, SNI.dll is locked until IIS process killed

**Comment by jakenuts** [comment]
Looking at the System.Data.SqlClient repository, there are some references to the necessity of holding onto and freeing the handle from SNI.dll (can't dig up where they load it). It doesn't appear that the handle loaded in Microsoft.Data.SqlClient is kept or later released which might explain why it sticks around.

From[ LocalDBAPI.Common.cs](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Data.SqlClient/src/System/Data/SqlClient/LocalDBAPI.Common.cs) in System.Data.SqlClient
``` c#
    //This is copy of handle that SNI maintains, so we are responsible for freeing it - therefore there we are not using SafeHandle
    private static IntPtr s_userInstanceDLLHandle = IntPtr.Zero;

   internal static void ReleaseDLLHandles()
   {
      s_userInstanceDLLHandle = IntPtr.Zero;
      s_localDBFormatMessage = null;
   }

```

**Comment by cheenamalhotra** [comment]
Thanks for the details @jakenuts 

I just opened up **System.Data.SqlClient** .NET framework library source code and I didn't see any call to "LoadLibrary" there (since our code is imported from there), here's the only way it's loaded for every API:

```cs
[DllImport("SNI.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "SNIAddProviderWrapper")]
internal static extern uint SNIAddProvider(SNIHandle pConn, ProviderEnum ProvNum, [In] ref uint pInfo);
```

Which is also present in our case in [SNINativeMethodWrapper.cs](https://github.com/dotnet/SqlClient/blob/580ac6262bf04b9bd6b1b93c9f4f5de0a7cc15e2/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs#L400)

I'm trying to understand why we added `LoadLibrary` call in there, which seems to be primary difference and cause of this behaviour.

**Comment by cheenamalhotra** [comment]
Hi @jakenuts 

I modified the way we load DLLs to test if we can fix the locking and still load SNI.dll properly, please try the NuGet package attached and let me know if you still experience lock:

[Microsoft.Data.SqlClient.2.0.0-dev.nupkg.zip](https://github.com/dotnet/SqlClient/files/3962611/Microsoft.Data.SqlClient.2.0.0-dev.nupkg.zip)

You can use this nuget package in your application by referencing as under:

`<PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.0-dev" />`

I'll proceed with PR once we have confirmation over expected behaviour.

**Comment by cheenamalhotra** [comment]
Hi @jakenuts 

I tried creating ASP.NET application to try reproduce issue but I cannot reproduce the problem using steps you mentioned above. I get file in use errors for "Roslyn" instead which I cannot delete, everything else I'm able to clean normally.

Application I tried:
[WebApplication1.zip](https://github.com/dotnet/SqlClient/files/3963121/WebApplication1.zip)

Can you provide me a simple application which you're able to reproduce with if I missed something as I'm new to ASP.NET MVC architecture.

**Comment by jakenuts** [comment]
Sorry, had to run out, missed that package (was dying to try it but life ran away with me). Here is the most minimal ASP.NET 4.8 app I could come up with (at least tonight) to demonstrate it. I stripped out all the MVC and other stuff and just open the connection in the Global.asax startup. If you load it up & restore the packages, run it in IIS it should show a mostly blank page and when you close it the SNI.dll will still be locked. As you mentioned the roslyn folder also locks at points, but it can be deleted when the web app is shut down. Let me know if that works.

[LockingWebApp48.zip](https://github.com/dotnet/SqlClient/files/3963330/LockingWebApp48.zip)

**Comment by jakenuts** [comment]
Sorry, I should have included that the Roslyn folder cannot be deleted while the app is running. Here is a minimal ASP.NET 4.8 project that demonstrates the issue (at least on my machine). You'll need to run it on IIS or IIS Express to reproduce the locking. I'm also connecting to Azure SQL in my connection string (stupidly posted that earlier, thus the deletion) but have replaced that with the localhost one from yours. Later I'll take a look at the two projects and see if there are any relevant differences.

[LockingWebApp.zip](https://github.com/dotnet/SqlClient/files/3964229/LockingWebApp.zip)

**Comment by jakenuts** [comment]
Here's another sample app that is even more 'minimal'. It uses owin and creates a connection to a non-existent LocalDb which is enough to use the SNI.dll imports. Once you open the project, restore the packages and run the app it should demonstrate the problem. Replacing the using statement for Microsoft.Data.SqlClient with System.Data.SqlClient resolves the issue.

[LockingWebApp.zip](https://github.com/dotnet/SqlClient/files/3965164/LockingWebApp.zip)

**Comment by cheenamalhotra** [comment]
Hi @jakenuts 

I tried your samples but still cannot reproduce any problem. 
I apparently have localdb installed, but I also tested with random server name in connection string just to trigger exception case. I don't see any locking problems with SNI.dll.

Just to confirm the steps:
1. Open application in VS and run with IIS
2. Stop debugging app
3. Delete `bin` and `obj` folders manually
   - I can delete totally fine!

My Environment details are:
- Windows 10 Enterprise
- Visual Studio Enterprise 2019 (16.4.1)
- .NET Framework 4.8.03752
- IIS Version 10.0.18362.1

Did I miss something?

P.S. I'm also checking with my team internally if someone can reproduce in their environment.

**Comment by jakenuts** [comment]
Thanks! I tried loading the project on a different machine and for whatever reason it differs in that "stop debugging" or closing the browser window also closes IISExpress which then releases the DLL. On my machine IISExpress stays active even after I've stopped debugging. 

When I tried with "Start without debugging" on the new machine, IISExpress stays active and when you try to rebuild, or if you delete all the rest of the files the SNI.dll remains locked. This replicates what is happening in production where full IIS remains running and once the dll is loaded it cannot be moved or updated until you kill the application pool.

**Comment by jakenuts** [comment]
I just tried creating an Azure App Service for the sample and published it there. Unfortunately it's way better at detecting changes than my VM deployment so it doesn't try to update the SNI.dll as they match so deployment succeeded without an issue. I was able to go into the console there and confirm that all the files in the bin directory could be deleted save for the SNI.dll though.

**Comment by cheenamalhotra** [comment]
Hi @jakenuts 

Yes I can reproduce the behavior now. The behavior with "**Start without Debugging**" happens because application is running on IIS in a detached mode and is **Active** on IIS Server from "bin" directory. What you mean to do it redeploy on top of **Active** application's "**bin**" directory. **SNI.dll** is locked in the process since it's a loaded library, from where you pointed above. Since the application is "**Active**", the DLL will stay loaded there.

If you stop the site, that would free the lock and **SNI.dll** can be deleted.

![image](https://user-images.githubusercontent.com/13396919/70937938-18686000-1ffa-11ea-8b5c-99e2a3fb64bf.png)

This seems to be expected behavior with Microsoft.Data.SqlClient.

With System.Data.SqlClient, you would not see this behavior because SNI code is inbuilt in "**System.Data.dll**" hence there was no external loading done. The Native SNI code in there is shared between all ADO.NET providers. This is not the case with **Microsoft.Data.SqlClient** as **SNI.dll** needs to be loaded from an external NuGet package "[Microsoft.Data.SqlClient.SNI](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI/)" in current process.

You can say that SqlClient (for .NET Framework) is incomplete without this referenced "**SNI.dll**". The reason why it's referenced externally from **Microsoft.Data.SqlClient** is that SNI native implementation continues to be a closed source, and is not open sourced yet.

**Comment by cheenamalhotra** [comment]
I was wondering if `SNI.dll` stayed loaded even after App was Shutdown/Stopped, as mentioned in the first comment, that doesn't seem to be the case.

**Comment by jakenuts** [comment]
It is a bit of a standout though as you can update/delete every file in a website (save for the roslyn folder) during deployment save for this one. Even after adding an App_Offline.htm file which is part of the standard deployment process the DLL remains locked so the only way to deploy is to stop the site entirely while the files are copied over. It's not a terrible workaround but it does mean that requests will come back with 500(?) responses instead of the App_Offline content which is slightly more polite.

Is it possible that the rest of the bin files are shadow copied somewhere such that they don't appear locked even when they loaded into the IIS process?

**Comment by cheenamalhotra** [comment]
I'm not an IIS expert, but there seem to be workarounds, with "Touch" tasks, you can try. I got some info from [Developer Community Post](https://developercommunity.visualstudio.com/content/problem/546858/bin-files-locked-by-iis-worker-process-1.html).

Ideally, as discussed on [Stack Overflow](https://serverfault.com/questions/6756/how-to-get-iis7-to-release-a-locked-file), the best approach is:
- Take the outage and allow IIS to cleanly release locks and clean up after itself to preserve server stability.
- If not feasible, you can either create another site on the same box, or set up a new box with the new content, and move the domain name/IP across to "promote" the new content to production.

**Comment by cheenamalhotra** [comment]
I will close the issue as the behaviour is "By Design".

Thanks!

**Comment by jakenuts** [comment]
It seems impervious to the App_Offline method, but I can live with the "restart application pool" workaround as I'm hoping to eventually migrate away from the 4.8 legacy bits anyway. I really appreciate your help, thanks, have a great holiday!

**Comment by vishnu4** [comment]
I'm surprised this issue is locked.  while it might be 'as it worked before' with the previous version of sqlclient, it's not really ideal behavior, right?  recycling the app pool isn't always reliable, and additionally  I hit this issue frequently on my development box on just compiling.

**Comment by cheenamalhotra** [comment]
Hi @vishnu4 

Firstly, this happens only with apps **active** or **running** in IIS, and you must **stop** the app safely in order to clean the _bin_ directory and recompile.

Secondly, Microsoft.Data.SqlClient (.NET Framework) needs to load native library Microsoft.Data.SqlClient.SNI (SNI.dll) and since it is not part of Full Framework it needs to be loaded explicitly to work. It is not unloaded due to the fact that driver cannot function at all without SNI.dll, and as I mentioned above their separation was done for security and legal reasons.

This design is not the same as System.Data.SqlClient, so even if you may think 'it worked before for S.D.S', technically, their designs are very different from each other.

Microsoft.Data.SqlClient (.Net Core) on the other hand also references SNI.dll from runtime native libraries but they're part of .NET Core SDK so you'll not encounter issues there. And since moving forward .NET Core is the primary focus and .NET Framework is not longer active, we recommend users to port over to .NET Core if this issue becomes a big hurdle in development.

**Comment by vishnu4** [comment]
I get that it happens when apps are active or running in IIS.  i'm not debating that.  I understand that the designs are very different as well, i'm not debating that either.  I'm just saying my use cases are not edge or unique, and even though i don't have a solution to this issue, i don't think it should be closed or ignored.

The 2 places i see this issue are:
- on deploy via azure devops, i've now added a 'recycle app pool' task, which runs fine, but SNI.dll was still seen as locked during some of my deploys (while it is trying to purge the bin directory).  so either the recycle wasn't good enough, or i need to change the task so that IIS is stopped entirely during the deployment process.  
- when i'm on my development machine I can run the app, work in it, and then rebuild again.  50% of the time my rebuild fails because the file is locked.  this definitely makes development difficult if i have to add the extra step of recycling the app pool or restarting IIS between every build.

I understand i'm in .net framework, and that is a purgatory that i should try to get myself out of, but the move to use microsoft.data.sqlclient was part of that move for me, but it's actually making the move harder because of these issues.  I have a large monolith .net framework app and i am gradually moving projects towards .net standard.  This gradual move is what is causing my issue apparently.

So the solution is that i can't move gradually?  I have to move everything to .net core immediately, all in one go without doing things in steps?  That just doesn't seem realistic, which is the only point i'm trying to make here.  This issue is making development more difficult, and the only solution seems  to be to move everything BACK to .net framework so i can use System.Data.SQLClient instead, which prevents me from ever really moving to .net core.  

.Net core is the primary focus.  Great, totally down with that.  Shouldn't that mean that aiding users from migrating from .Net Framework to .Net core should be important then?

**Comment by cheenamalhotra** [comment]
Reopening as we're considering a solution to allow unload of sni.dll - WIP

**Comment by agevorg** [comment]
Hi @cheenamalhotra ,
Do you have any ETA for this to be solved? We are waiting this issue to be solved to update our 2.1 version to 3.1.

**Comment by chumacn** [comment]
is this issue be solved? we are waiting for this. to update to 3.1

**Comment by chumacn** [comment]
for develop debug condition ,temporary solution：

before you rebuild project，execute the bat，then sni.dll will be unlocked

bat content:
c:\windows\system32\inetsrv\AppCmd.exe stop apppool /apppool.name:"your pool name"
ping -n 5 127.1>nul
c:\windows\system32\inetsrv\AppCmd.exe start apppool /apppool.name:"your pool name"

**Comment by cheenamalhotra** [comment]
Hi @agevorg @chumacn 

We investigated the same and currently the driver design does not support implementing unload behavior since the DLL is loaded in a static class instance. A great deal of changes are needed in the driver to support this, and that hasn't been prioritized yet.

Recommended solution with this design is to undeploy and re-deploy your app in IIS to perform safe unload of SNI.dll.

**Comment by chumacn** [comment]
> Hi @agevorg @chumacn
> 
> We investigated the same and currently the driver design does not support implementing unload behavior since the DLL is loaded in a static class instance. A great deal of changes are needed in the driver to support this, and that hasn't been prioritized yet.
> 
> Recommended solution with this design is to undeploy and re-deploy your app in IIS to perform safe unload of SNI.dll.

so when update to fix？previous version work well。but the latest version do lock the dll

**Comment by jimbromley-avanade** [comment]
Hi @cheenamalhotra; Just chiming in that this issue is blocking others as well. As large projects are not always dynamic and able to shift as quickly there is an expectation of status quo from the behavior and deployment process. Please consider this another vote to raise the priority for this issue. 

Thanks!

**Comment by steinmr** [comment]
Hi @cheenamalhotra, just chiming in with our experiences. Our case is slightly different, and harder to work around.  We cannot currently move to full .NET Core for this application (it is big) and we cannot use the System.Data.SqlClient.dll either because we want to use EFCore.

We load libraries into separate appdomains, and later unload them to upgrade them without restarting the entire process. But since SNI.dll is locked, we are unable to update those libraries after the appdomain is unloaded.
We are using shadow copy, but SNI.dll is not shadow-copied.

I have create a reproduction repo here: https://github.com/steinmr/SNILockedRepro

**Comment by cheenamalhotra** [comment]
Hi @steinmr @jimbromley-avanade 

I understand your concerns. We have been investigating on making this experience better but the problem is the fact that this is Native/Unmanaged DLL that is loaded in the IIS process.

We also managed to remove the `LoadLibrary()` call (changes will be merged with PR #570) but because this is a Native DLL, once loaded by the application, it stays loaded.

We have limited experience with IIS but how do you normally work with Native DLLs and unload them from process without unloading them from managed code? Have you used solutions involving  common directory like `C:\Windows\System32\inetsrv` outside your `bin` folder such that your local `bin` can be safely deleted?

I'm wondering because we're now moving away from strong path `LoadLibrary()`, and would be able to load DLL if it's loaded in the process from any directory, maybe this could bring a potential solution?

**Comment by steinmr** [comment]
@cheenamalhotra Than you for your assistance. I tried the PR, but now I can not delete ``Microsoft.Data.SqlClient.SNI.x64.dll``

**Comment by cheenamalhotra** [comment]
@steinmr 

Yes the problem is going to stay if you use it as it is because DLLs are still going to be copied with the driver. As I said earlier, what's changed is we do not `LoadLibrary()` from strong path in the new design.

Have you tried to move `Microsoft.Data.SqlClient.SNI.x64.dll` to a different location that's also loaded in IIS, rather than keeping it in the same `bin` folder?

**Comment by steinmr** [comment]
@cheenamalhotra Hi, thank you for your continued help, really appreciated. 

Just to be clear, I'm not using IIS, this is a simple console app.

We do not currently have any special handling for native DLLs, as far as I know all DLLs are either managed or part of the full .NET framework.

But with the following modifications to my example repo, I was able to "shadow copy" the native DLL, and thus it was loaded from the shadow-copied folder, instead of the bin folder. This means that it fixes my problem. This requires PR #570 
But this feels pretty clunky, and I agree with @vishnu4 that such issues will be blockers for moving over to netcore, which is the end goal for all of us I think.

```csharp
private static AppDomain CreateAppDomain(FileInfo file)
{
    var appDomainSetup = new AppDomainSetup { ShadowCopyFiles = "true" };
    var appDomain = AppDomain.CreateDomain(file.Name, null, appDomainSetup);
    appDomain.AssemblyLoad += AppDomain_AssemblyLoad;
    return appDomain;
}

private static void AppDomain_AssemblyLoad(object sender, AssemblyLoadEventArgs args)
{
    const string lib = "Microsoft.Data.SqlClient";
    if(args.LoadedAssembly.ManifestModule.Name == $"{lib}.dll")
    {
        foreach (var file in new string[] { $"{lib}.SNI.x64.dll", $"{lib}.SNI.x86.dll" })
        {
            var targetFile = Path.Combine(Path.GetDirectoryName(args.LoadedAssembly.Location), file);
            if(!File.Exists(targetFile)) // Shadow copy native DLL
                File.Copy(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, file), targetFile);
        }
    }
}
```

**Comment by cheenamalhotra** [comment]
Hi @jakenuts 

That sounds great!

Just to clear your doubts, in .NET Core you will not have these issues as there we have runtime native DLLs which are loaded in process from NuGet Package cache folders and there is no transitive copy performed. You can give it a try in example apps and let us know if you face any issues.

These DLLs and issues associated with it are only applicable to .NET Framework and it is this transition phase that I believe is a little difficult to configure but with improvements we are coming with in #570 we hope to make the transition process smoother.

**Comment by steinmr** [comment]
Thanks  @cheenamalhotra 

Any plans on adding this to 1.1 in addition to 2.0?

**Comment by cheenamalhotra** [comment]
Hi @steinmr 

This change required good amount of design changes in both SNI packaging and driver consumption and isn't a patch.. so no, backporting wouldn't be possible. This shall be available starting v2.0.

**Comment by berezovskii** [comment]
Hello @cheenamalhotra, 
I faced the same issue on IIS.
I updated the Microsft.Data.SqlClient and Microsft.Data.SqlClient.SNI to the 2.0.0 version but the Microsoft.Data.SqlClient.SNI.x64 is still locked by the IIS.
Do you have any thoughts on why it happened?

**Comment by ssg** [comment]
This breaks our build pipeline because our unit tests encounter the same problem. We are trying to progressively migrate to .NET Core and migrating to EF Core was one of the planned milestones for that. We have no way to migrate to EF Core without this issue fixed. Is there any workaround?

**Comment by cheenamalhotra** [comment]
@berezovskii @ssg 

The above comment(https://github.com/dotnet/SqlClient/issues/354#issuecomment-632312605) is a workaround to perform shadow copy of DLLs to a different folder and load DLLs from there. That way an App redeployment wouldn't be obstructed with loaded DLLs.

**Comment by FreshPrinceMayo** [comment]
Hi, faced this issue also. 

If anyone is using TFS to deploy their applications I updated IIS Web App Deploy task as a workaround until a better solution is found. 

`-usechecksum`


![image](https://user-images.githubusercontent.com/64701085/90137277-1b307600-dd7e-11ea-8f06-fac3ff7fe9d4.png)

**Comment by rbiq** [comment]
Hi, is this issue resolved? I'm still receiving this error on ASPNET 4.8 using Microsoft.Data.SqlClient 2.0.1.

**Comment by cheenamalhotra** [comment]
@rbiq 

The only resolution to this issue is to not have an external Native dependency in use at all, which is an ultimate long term goal for us but extremely unlikely in near sight future. Native SNI Dlls are very stable/performant in every way and it's extremely hard to replace them. Even if we start today, it will take a very long time of testing/improvements in order to build trust in customer applications before it's officially replaced, and this effort is not planned yet for .NET Framework. The Managed implementation we have for .NET Core driver is also under constant improvements/testing, but it has it's own challenges to overcome to be comparable with native implementation.

As of possible mitigations in current state, they are detailed in above discussions.

**Comment by rbiq** [comment]
@cheenamalhotra I guess I can continue to kill w3wp.exe in development environment to overcome the issue. However what i'm really trying to understand is the impact of this in production. Currently we're deploying manually to our product environment which entails pasting the bin folder manually. Will this cause any unforeseen issues in there? Also i believe this was a dependency on Microsoft.Data.SqlClient when I installed it from nuget in a .netstandard 2.0. This netstandard library is referenced in the aspnet 4.8 web app project. So if I replace this lib with good old System.Data.SqlClient will this issue go away? I think EF Core installed in the netstandard should still work with System.Data.SqlClient, amiright?

**Comment by cheenamalhotra** [comment]
I don't see any issues with manual deployment if it's designed this way. If you want it automated, you'd need some downtime to stop the application - deploy and restart, which is also possible solution. If you downgrade driver to System.Data.SqlClient, it would solve the bin directory issue because the driver is not loaded from there, but from framework itself. But you'll also have to also downgrade EF Core version and I wouldn't recommend doing that just for deployment ease.

The best advisable solution is to load SNI dlls from any another directory other than bin directory by shadow copying them to that directory. That will not block you to redeploy application as native DLLs will not be loaded from that location. The driver loads them to the bin directory as that's the only directory driver is eligible to access, but you can control that and place it to any other location that you don't expect to block you. Do remember to replace the SNI dlls when you upgrade version of Microsoft.Data.SqlClient (if SNI reference also updates), to make sure you're getting all updates from native side too.

**Comment by rbiq** [comment]
Understood. thanks for the response. I'm currently developing on NET48 classic Webforms aspx and deploying on IIS. To my understanding the AppDomain is more or less managed by IIS and so I'm not sure where I would apply the above steps to launch an appdomain and shadow copy the file. Can you please shed some light on it? thanks for all your help.

**Comment by matrimsaric** [comment]
This is going to make development irritating for a large team for the next few months :( Thankfully we are just switching to Standard as an intermediate step between  moving to Core at some point next year so at least will be able to say 'it's only for a few months hopefully'

I find the best way to clear the lock is kill the w3wp.exe for the relevant user in TaskManager>>Details. Shutting the IIS site or stopping the relevant app pool does not prevent the issue (in our case we build into IIS from TFS so are often 'changing' code and re-building so will hit this a lot)

It might be possible to automate this to 'hide' the problem. So I will try to look at that next.

**Comment by cheenamalhotra** [comment]
@rbiq 

It is not our expert area to advise on .NET WebForms and IIS application design. I'd recommend seeking advice on design ideas from experts in IIS application area.

**Comment by matrimsaric** [comment]
I found the easiest way to clear the process lock was to force IIS reset in one of the project builds

<PropertyGroup>
  <PreBuildEvent>iisreset /stop</PreBuildEvent>
</PropertyGroup>
  <PropertyGroup>
    <PostBuildEvent>
iisreset /restart
    </PostBuildEvent>

Stops the error occurring and allows the build to occur. Might have secondary advantages in ensuring IIS doesn't have any hangups with previous operations as well.

**Comment by matrimsaric** [comment]
To avoid our devs having to manually kill the process we have added an iisreset command to one of the project builds which will nicely avoid the problem.

```
<PropertyGroup>
  <PreBuildEvent>iisreset /stop</PreBuildEvent>
</PropertyGroup>
  <PropertyGroup>
    <PostBuildEvent>
iisreset /restart
    </PostBuildEvent>
  </PropertyGroup>
```

**Comment by rbiq** [comment]
@matrimsaric unfortunately we're seeing:
The command "iisreset /restart" exited with code 5. Please verify that you have sufficient rights to run this command.
Did you face the same issue? If so, how did you build it in admin mode?

**Comment by rbiq** [comment]
> @rbiq
> 
> It is not our expert area to advise on .NET WebForms and IIS application design. I'd recommend seeking advice on design ideas from experts in IIS application area. You may find some helpful tips from the discussion above.

Unfortunately this issue doesn't seem to be related to webforms and iis per se. This is about referencing MDS into webforms and how it works with webforms. If you could write a hack to unload the dll when app domain is being shutdown and provide that as an additional dll to load along with MDS and other refs that'd solve our problem.

**Comment by rbiq** [comment]
@matrimsaric no luck with that either. It won't run. At this point I'm resorting to running a batch file manually before every build. It sucks and Microsoft should really do something about this hindrance.

**Comment by tbolon** [comment]
I think you should mention someone from the asp.net team, preferably someone who worked previously on the asp.net fwk team.

The concept of shadow copy is here to handle the case of dll locking. Perhaps the native library could be included as a shadow copy member and then be loaded from the DynamicBase directory which will be different from the current directory you deployed your application in (see https://shazwazza.com/post/Developing-a-plugin-framework-in-ASPNET-with-medium-trust.aspx for example).

The concept of shadow copy is to copy the files from the app in a unique directory where locking could occurs. Then, original directory is still writable and when a new app is started, a new directory will be created.

I am sure there are people at MS which could help you handle this better in a IIS / ASP.NET scenario.

**Comment by Tasteful** [comment]
Based on the comments from https://stackoverflow.com/questions/2445536/unload-a-dll-loaded-using-dllimport I was creating the following class and then call the `Microsoft.Data.SqlClient.SniUnloader.RegisterForUnload()` method from the Init-method in the global.asax and this releasing the locked SNI-assembly when I test with the rebuild solution inside Visual Studio.

```cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;

namespace Microsoft.Data.SqlClient
{
    public static class SniUnloader
    {
        private static bool _registered;
        private static readonly object _registrationLock = new object();

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool FreeLibrary(IntPtr hModule);

        public static void RegisterForUnload()
        {
            if (!_registered)
            {
                lock (_registrationLock)
                {
                    if (!_registered)
                    {
                        AppDomain.CurrentDomain.DomainUnload += CurrentDomain_DomainUnload;
                        _registered = true;
                    }
                }
            }
        }

        private static void CurrentDomain_DomainUnload(object sender, EventArgs e)
        {
            var moduleName = Environment.Is64BitProcess
                ? "Microsoft.Data.SqlClient.SNI.x64.dll"
                : "Microsoft.Data.SqlClient.SNI.x86.dll";

            ProcessModule module =
                Process.GetCurrentProcess().Modules.OfType<ProcessModule>()
                    .FirstOrDefault(x => x.ModuleName == moduleName);

            if (module is object)
            {
                FreeLibrary(module.BaseAddress);
            }
        }
    }
}
```

**Comment by matrimsaric** [comment]
nice! I tried your code in my own project and have not hit any issues yet (I am calling it prior to the Configuration if that makes any difference). I also have the force IIS reset in the build process as a further complicating factor.

**Comment by ssinfod** [comment]
Hello @cheenamalhotra

For me, this seems to be a bug in the .NET Core framework (SqlClient). Actually, an unmanaged ressource that is not released properly. Is this exact ?

I'm currently having deployment issue with Azure Devops that seems to be related to this problem:
![image](https://user-images.githubusercontent.com/10925073/113323468-faed0180-92e3-11eb-9558-978a859710d4.png)

Is there any plan to release a fix for this problem ?

Thanks for your help,

**Comment by mrdaneeyul** [comment]
> The below code was not working but creating an IIS module that shadow copy the DLL was working much better, see https://github.com/Tasteful/SNILoader

How/where does this SNILoader fit into the code? Is this a project you add to an existing solution? You said it's an IIS module, but I can't figure out how to install it as a module to IIS.

**Comment by mrdaneeyul** [comment]
> The below code was not working but creating an IIS module that shadow copy the DLL was working much better, see https://github.com/Tasteful/SNILoader

@Tasteful, how/where does this SNILoader fit into the code? Is this a project you add to an existing solution? You said it's an IIS module, but I can't figure out how to install it as a module to IIS.

**Comment by Tasteful** [comment]
> > The below code was not working but creating an IIS module that shadow copy the DLL was working much better, see https://github.com/Tasteful/SNILoader
> 
> @Tasteful, how/where does this SNILoader fit into the code? Is this a project you add to an existing solution? You said it's an IIS module, but I can't figure out how to install it as a module to IIS.

1. Build and package the project into a nuget-package. If you publish the package, think of reading and understand the license for the different included components.
2. Add a reference to the created nuget-package and make a clean build of the solution.
3. Ensure that the SNI-dll file not exists in the bin-folder. 
4. Test your solution to ensure that it is working with the shadow copying of the SNI-dll into the temporary folders for ASP.NET files.

When deploying into production for the first time the SNI-dll will still be there in the bin-folder and block the deployment and you need to do some workaround to get the files updated.

**Comment by mrdaneeyul** [comment]
> 1. Build and package the project into a nuget-package. If you publish the package, think of reading and understand the license for the different included components.
> 2. Add a reference to the created nuget-package and make a clean build of the solution.
> 3. Ensure that the SNI-dll file not exists in the bin-folder.
> 4. Test your solution to ensure that it is working with the shadow copying of the SNI-dll into the temporary folders for ASP.NET files.
> 
> When deploying into production for the first time the SNI-dll will still be there in the bin-folder and block the deployment and you need to do some workaround to get the files updated.

This worked perfectly. Thank you!

**Comment by lscorcia** [comment]
Hitting this issue here. Not using azure but xcopy deployment on premises with fw 4.7.2. It seems to me that the shadow copy mechanism that was so useful under .netfw was completely forgotten while designing .net core. I am hitting so many unexpected issues with these porting steps that I'm starting to think if it would be easier to just hand out the rewrite to our java team :-(

**Comment by lscorcia** [comment]
But my application is not running under .net core: it is running under the full .net 4.7.2 framework/IIS. One would expect that the native library would be unloaded when IIS recycles the application, but it does not. 
I tried with the usual workarounds, like placing an app_offline.htm in the app root, or touching the web.config file - they do not work either, the file remains locked. Only a full Application Pool restart seems to unlock the file. 
Basically, using this component breaks xcopy development on the .net framework.

I don't see how reaching the .net core team would help: the previous comments suggest that this component does not unload the library when the AppDomain is recycled. It is not an issue with the runtime, as shadow copy/xcopy deployment usually works fine on the full framework.

**Comment by tbolon** [comment]
> It seems to me that the shadow copy mechanism that was so useful under .netfw was completely forgotten while designing .net core.

Please also note that [Shadow Copying is planned for .NET 6](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/#shadow-copying-in-iis).

**Comment by tbolon** [comment]
Based on the fact that shadow copying is now planned for .NET 6, maybe the team could try to see if there could be a mechanism to detect and use the native library from the shadow copy location instead of the original location?

This solution could be useful for .net fwk cases, but also for future .net 6 web apps. I am sure the .net team could gladly help for this kind of scenarios.

**Comment by lscorcia** [comment]
I only tested it for a couple of days, but I think I found an elegant solution to enable the shadow copy mechanism for the native assembly. I will publish on github it in the next few hours.

**Comment by Tasteful** [comment]
@lscorcia something similar to my https://github.com/Tasteful/SNILoader ?

**Comment by lscorcia** [comment]
I published my approach at https://github.com/lscorcia/sqlclient.snishadowcopy . It is similar to @Tasteful approach in the sense that it copies the native assembly under the shadow folder, but it takes advantage of the fact that Windows will first try to load the dll from the same location of the Microsoft.Data.SqlClient assembly so by copying the native assembly there, no explicit call to LoadLibrary is needed.

If anyone could confirm that this approach is actually working and it's not just a fluke in my tests, I would go on and publish a Nuget package.

Thanks!

**Comment by bahman616** [comment]
> I published my approach at https://github.com/lscorcia/sqlclient.snishadowcopy . It is similar to @Tasteful approach in the sense that it copies the native assembly under the shadow folder, but it takes advantage of the fact that Windows will first try to load the dll from the same location of the Microsoft.Data.SqlClient shadow assembly - so by copying the native assembly there, no explicit call to LoadLibrary is needed, and it is not necessary to redistribute the SNI libraries as resources.
> 
> If anyone could confirm that this approach is actually working and it's not just a fluke in my tests, I would go on and publish a Nuget package.
> 
> Thanks!

This worked well for us! Thank you for sharing your solution!

**Comment by StevenQuickGS1** [comment]
> I published my approach at https://github.com/lscorcia/sqlclient.snishadowcopy . It is similar to @Tasteful approach in the sense that it copies the native assembly under the shadow folder, but it takes advantage of the fact that Windows will first try to load the dll from the same location of the Microsoft.Data.SqlClient shadow assembly - so by copying the native assembly there, no explicit call to LoadLibrary is needed, and it is not necessary to redistribute the SNI libraries as resources.
> 
> If anyone could confirm that this approach is actually working and it's not just a fluke in my tests, I would go on and publish a Nuget package.
> 
> Thanks!

Worked for me also in .net 4x mvc5 app in global.asax

**Comment by JRahnama** [comment]
@jakenuts is this still an issue or the solution provided by @lscorcia solved your issue? If the issue is solved please feel free to close the issue.

**Comment by waf** [comment]
It's still an issue I'd say, having a locked file on the filesystem causes all sorts of development time and operational issues. They can be worked around (e.g. https://github.com/lscorcia/sqlclient.snishadowcopy) but it's a pretty poor experience by default.

Possibly the SqlClient project could start using the shadow copy approach that @lscorcia showed?

**Comment by macwier** [comment]
Has anyone tried adding explicit reference to Microsoft.Data.Sql **2.x**? 
I'm comming from a bit different issue, but seems like it could be a solution here as well.

**Comment by EikeStein** [comment]
The workaround by @lscorcia didn't work for me. I don't have a Microsoft.Data.SqlClient.x86.SNI.dll, but 
Microsoft.Data.SqlClient.dll and the SNI.dll in a subfolder x86.
If I remove the SNI.dll from the x86 folder the app crashed when I try to access the database because the dll is not found, even if I copy it to the shadow copy location (it appears it always searches in the bin folder). Any ideas?

**Comment by JRahnama** [comment]
@EikeStein is this referring to `Microsoft.Data,SqlClient` or `System.Data.SqlClient`?

**Comment by EikeStein** [comment]
> @EikeStein is this referring to `Microsoft.Data,SqlClient` or `System.Data.SqlClient`?

To Microsoft.Data.SqlClient (unless I'm totally lost)

**Comment by sinanaltaii** [comment]
I have the same issue with Visual Studio 2022. When I try to clean the project, I get the message 

Unable to delete file "bin\Microsoft.Data.SqlClient.SNI.x64.dll". Access to the path 'C:\myprojcts\WebApplicationProject.Web\bin\Microsoft.Data.SqlClient.SNI.x64.dll' is denied.

**Comment by DomZZ** [comment]
Same here, we have a big solution in .NET 4.6.2, we are doing early steps to move on .NET Core. 
But Microsoft is doing is best to prevent us to switch on .NET Core :-(

**Comment by shazadishaque** [comment]
> Ran into the same issue - website running in IIS and doing a rebuild in VS would error out on cleaning the bin folder because the SNI dll is locked.
> 
> Normally IIS copies all the dlls to some temp directory like "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\8b727de3\bc3cd64\assembly\dl3\52c41fab\0079fa1e_3661d901" a runs it from there. That way the original bin folder can be cleared and rebuild. For some reason this isn't happening for these SNI dlls.
> 
> I came up with this workaround (needs to be run somewhere at start, before anything loads the SqlClient dlls):
> 
> ```
> [System.Diagnostics.Conditional("DEBUG")]
> private static void FixSqlClientRebuild()
> {
>     var assembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(x => x.GetName().Name == "Microsoft.Data.SqlClient");
>     if (assembly is not null)
>     {
>         var folder = Path.GetDirectoryName(assembly.Location);
>         var path = Path.Combine(folder, "Microsoft.Data.SqlClient.SNI.x64.dll");
>         var dll = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "bin", "Microsoft.Data.SqlClient.SNI.x64.dll");
>         File.Move(dll, path);
>     }
> }
> ```
> 
> Basically just moving the dll from the bin folder to the temp location where "Microsoft.Data.SqlClient.dll" is.

We've experienced the same problem after migrating to Microsoft.Data.SqlClient. When we launch the app it loads fine but IIS Express holds a lock on the Microsoft.Data.SqlClient.SNI.x64.dll. When recompiling our .Net Framework 4.6.2 WebForms app, due to the lock we get the error "Unable to delete file "bin\Microsoft.Data.SqlClient.SNI.x64.dll". Access to the path '..\bin\Microsoft.Data.SqlClient.SNI.x64.dll' is denied."

I tried @lscorcia's workaround but it didn't work for us. I tried @jaryn-kubik's workaround and it works!! We can now recompile our project in visual studio without the compilation error occurring. 

As someone previously mentioned in this thread, this compilation error only occurs for WebForms projects and it works fine in .Net Core. I hope to remove this patch when we eventually upgrade to .Net Core.

**Comment by matdavies** [comment]
To add our experience to this thread in case it helps anyone. 

Like @EikeSchwass ([comment](https://github.com/dotnet/SqlClient/issues/354#issuecomment-1058089006)), we were using a version of `Microsoft.Data.SqlClient` (1.1.X) that copied `x86\SNI.dll` and `x64\SNI.dll` assemblies into the bin folder, and caused IIS to lock them there.  In versions of `Microsoft.Data.SqlClient` prior to 2.0-preview4 (per @Kaur-Parminder 's [comment](https://github.com/dotnet/SqlClient/issues/354#issuecomment-1071172322)) the SNI.dlls are loaded from the bin directory no matter what you do (owing to a [hard coded path](https://github.com/dotnet/SqlClient/blob/55a271931c4c27b572b2e75229e8274a758aca40/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs#L55-L67) in the static constructor of `SNINativeMethodWrapper`.

So, in order to use @lscorcia 's [workaround](https://github.com/dotnet/SqlClient/issues/354#issuecomment-822446144), we needed to update the version of `Microsoft.Data.SqlClient` we were using.  I tried to upgrade to 3.1.5 first, but when doing so, ended up with errors connecting to the database via EntityFramework ("error: 26 - Error Locating Server/Instance Specified").  So I updated to 4.1.5 which worked, but with the caveat that there is a breaking change; specifically, versions of `Microsoft.Data.SqlClient` > 4.0.0 assume that the connection will be encrypted, so if it is not, you either need to make it so, or add "Encrypt=false" to the end of your connection string.

Hope that helps someone else.  Not a fun issue to diagnose and fix...

**Comment by ProVega** [comment]
With the release of 5.2 does any know if this issue was fixed?

**Comment by omccully** [comment]
@ProVega I'm using v5.2.0 and .NET Framework 4.8 and still experiencing it. Although one of our apps using 5.2.0 has not experienced it and one of them is, and I can't figure out why. They're running on different servers. Perhaps different IIS versions, not sure. Not sure what else would make the difference.

**Comment by cuttercroix** [comment]
@ProVega  I'm using 5.2.0 on .net Framework 4.7.2 and it still happens. This whole thread is very frustrating. We are stuck on the full framework due to Microsoft's choices. I am trying to leverage new authentication modes to increase our application security which is only supported in Microsoft.Data.Sql, and now our development workflow is degraded. 

And doing iisReset's fails half the time telling me I'm not an admin (which I am),

**Comment by jberke** [comment]
@ProVega still broken on 4.7.2 using 5.2.0 of Microsoft.Data.SqlClient. 
Iscorcia's solution worked https://github.com/lscorcia/sqlclient.snishadowcopy. We are using OWIN so I tied into Owins Configuration class. Copied his one class into my project and it seems to be working!

Thank you @Iscorcia I owe you a beer!

**Comment by cheenamalhotra** [comment]
We're closing the issue as there are no plans to address this in .NET Framework SNI DLLs.
There are solutions discussed in the thread that should help mitigate the issue.

**Comment by caspChristian** [comment]
@cheenamalhotra how can you say that the old sql package is obsolete, and we must upgrade, and then not actually make sure it is working?
This issue MUST be fixed, or retract the statement that we should upgrade.
It is also beyond me that you are using non managed parts for the sql client Reopen and fix ASAP!

**Comment by oconnor0** [comment]
This is disappointing. The new library, Microsoft.Data.SqlClient, is in important ways worse than the old, deprecated library, System.Data.SqlClient. The "new" library both has more dependencies and has this weird DLL locking issue which requires various attempted workarounds.
