### ISSUE TITLE
Active Directory Interactive doesn't work with .NET 10 on macOS

### ISSUE THREAD

**Issue by jrr** [dotnet/SqlClient#3820]
### Describe the bug
When you use [interactive authentication](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver17#using-interactive-authentication) (e.g. `Authentication="Active Directory Interactive"` in your connection string), a browser is supposed to pop up to sign in to your Microsoft account. This works on .NET 9, but fails on .NET 10 with a `System.PlatformNotSupportedException`:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): macOS 26.1.0
 ---> System.PlatformNotSupportedException: macOS 26.1.0

Microsoft.Data.SqlClient.SqlException (0x80131904): macOS 15.6.1
 ---> System.PlatformNotSupportedException: macOS 15.6.1
```

<details>
<summary>Call stack</summary>

```
Microsoft.Data.SqlClient.SqlException (0x80131904): macOS 26.1.0
 ---> System.PlatformNotSupportedException: macOS 26.1.0
   at Microsoft.Identity.Client.Platforms.netstandard.NetCorePlatformProxy.StartDefaultOsBrowserAsync(String url, Boolean isBrokerConfigured)
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.<>c__DisplayClass10_0.<InterceptAuthorizationUriAsync>b__0(Uri u)
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.InterceptAuthorizationUriAsync(Uri authorizationUri, Uri redirectUri, Boolean isBrokerConfigured, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.AcquireAuthorizationAsync(Uri authorizationUri, Uri redirectUri, RequestContext requestContext, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.AcquireTokenInteractiveDeviceFlowAsync(IPublicClientApplication app, String[] scopes, Guid connectionId, String userId, SqlAuthenticationMethod authenticationMethod, CancellationTokenSource cts, ICustomWebUi customWebUI, Func`2 deviceCodeFlowCallback)
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider.AcquireTokenAsync(SqlAuthenticationParameters parameters)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.<>c__DisplayClass147_1.<<GetFedAuthToken>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OnFedAuthInfo(SqlFedAuthInfo fedAuthInfo)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext _, TState s)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetAppliedMigrations(DatabaseFacade databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetPendingMigrations(DatabaseFacade databaseFacade)
   at (application code here)
```
</details>

### To reproduce
Attempt to connect to an Azure SQL Server with [interactive authentication](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver17#using-interactive-authentication), e.g. through EF Core.

### Expected behavior

A browser should pop up, like it does with .NET 9

### Further technical details
Microsoft.Data.SqlClient version: 6.1.3
.NET target: .NET 10
SQL Server version: Microsoft SQL Azure (RTM) - 12.0.2000.8 
Operating system: macOS 26.1

**Additional context**
I think the problem is in [AzureAD/microsoft-authentication-library-for-dotnet](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) (nuget `Microsoft.Identity.Client`), but filing here because `Microsoft.Data.SqlClient` is the library my application has a direct relationship with.

Related:
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5590
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4890
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/5541

**Comment by mdaigle** [comment]
Hi @jrr, thanks for bringing this to our attention. Since the problem reproduces using just MSAL, I agree that the problem is likely there. I'll keep an eye on those issues and implement an appropriate fix based on the resolution there.

In the meantime, can you tell me a little bit more about your project and your use case for interactive auth?

**Comment by jrr** [comment]
On our current project, interactive auth is used by developers, connecting a locally-running application to an Azure database. (when deployed, the app uses other mechanism(s)).

**Comment by mdaigle** [comment]
Got it. Do you typically run the app directly from the command line? or do you use visual studio (or some other ide)? I'm curious how the embedded browser popup behavior has been working for you and if you've ever seen any issues.

Also, are you aware of [authentication brokers](https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/desktop-mobile/wam#what-is-a-broker)? It offloads token management to the OS and can help avoid having to re-enter credentials all the time. It's not very well supported for mac at the moment, but we're looking at enabling this for windows in the near future. Would something like this be useful for your dev workflow or has the embedded browser been sufficient?

**Comment by jrr** [comment]
Running both through the CLI and interactively in JetBrains Rider, it's been fine until now! The browser launching looks [pretty unsophisticated](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/522d9ced0717443b6e99ab4f259b9b4039218ddf/src/client/Microsoft.Identity.Client/Platforms/netstandard/NetCorePlatformProxy.cs#L230). I hadn't heard of authentication brokers, but the whole team is on Macs, so it might be a while before that brings any relief.

**Comment by cheenamalhotra** [comment]
Looks like [Microsoft.Identity.Client v4.80.0](https://www.nuget.org/packages/Microsoft.Identity.Client/4.80.0) fixes this issue, as discussed [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5590#issuecomment-3715594333).

@paulmedynski @mdaigle something to consider while updating dependencies.


_P.S. a direct reference to MSAL v4.80.0 should fix this issue for anyone encountering this._

**Comment by paulmedynski** [comment]
This PR changed the macOS detection to the broken behaviour on May 1, 2025:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/5051

It looks like the behaviour previous to that PR would have worked on .NET 10.

That PR appears to have been included in v4.72.0:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/compare/4.71.1...4.72.0

So if you are using a version prior to that, it will likely work with .NET 10.  (There may be other issues with .NET 10 and those older versions - I haven't tried.)

For MDS 7.0.0, we will use the latest MSAL version, at least 4.80.0.

For MDS servicing versions, here's the MSAL version we're currently using, and what we plan to do:

<table>
<tr>
 <th>MDS Version
 <th>MSAL Version
 <th>Dependency Type
 <th>Plan
 <th>Comments
<tr>
 <td>6.1.3
 <td>4.73.1
 <td>Transitive
 <td>Upgrade MDS 6.1.4 to a direct dependency on MSAL 4.80.0
 <td>This will bring in major version bumps of other packages.
<tr>
 <td>6.0.4
 <td>4.73.1
 <td>Transitive
 <td>Upgrade MDS 6.0.5 to a direct dependency on MSAL 4.80.0
 <td>This will bring in major version bumps of other packages.
<tr>
 <td>5.1.8
 <td>4.76.0
 <td>Direct
 <td>No plan to upgrade.
 <td>
</table>

**Comment by paulmedynski** [comment]
It appears that MSAL 4.80.0 is still a problem on macOS:  https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5590#issuecomment-3985653500

We should still update our dependency - in the new Azure package - and use whatever the latest version available is.  We will continue to monitor the [MSAL issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5590), and we can now easily release an updated Azure package if/when MSAL is fixed.

**Comment by jrr** [comment]
For what it's worth, my team's problem can be worked around by pinning `Microsoft.Identity.Client` to >= 4.80.0. If I remove the pin, then the transitive dependency resolves to a lower, still-symptomatic version.

**Comment by cheenamalhotra** [comment]
We will be updating to newer version in the next release, dependency updates are planned with #3796.
